### ISSUE TITLE
brick:Limit has two skos:definitions

### ISSUE THREAD

**Issue by jbulow** [BrickSchema/Brick#403]
brick:Limit has two skos:definitions:

`    skos:definition "A parameter that places a lower or upper bound on the range of permitted values of a Setpoint."@en,
        "A parameter that places an upper or lower bound on the range of permitted values of another point"@en ;
`

**Comment by gtfierro** [comment]
I believe this is fixed in #348!

**Comment by jbulow** [comment]
This is still an issue.  One definition comes from line 607 in definitions.csv:
```
https://brickschema.org/schema/Brick#Limit,A parameter that places an upper or lower bound on the range of permitted values of another point,
```

And the other definitions seems to come from the brickschema pip package:

```
./venv/lib/python3.10/site-packages/brickschema/ontologies/1.3/Brick.ttl:44680:    skos:definition "A parameter that places a lower or upper bound on the range of permitted values of a Setpoint."@en,
./venv/lib/python3.10/site-packages/brickschema/ontologies/1.2/Brick.ttl:18988:    skos:definition "A parameter that places a lower or upper bound on the range of permitted values of a Setpoint."@en,
./venv/lib/python3.10/site-packages/brickschema/ontologies/1.1/Brick.ttl:12534:    skos:definition "A parameter that places a lower or upper bound on the range of permitted values of a Setpoint."@en,
```

The resulting `Brick.ttl` will get:

```
brick:Limit a owl:Class,
        sh:NodeShape ;
    rdfs:label "Limit" ;
    rdfs:subClassOf brick:Parameter ;
    skos:definition "A parameter that places a lower or upper bound on the range of permitted values of a Setpoint."@en,
        "A parameter that places an upper or lower bound on the range of permitted values of another point"@en ;
...
```

**Comment by steveraysteveray** [comment]
Actually, I see 4 such cases:
brick:Max_Supply_Air_Temperature_Setpoint_Limit
brick:Min_Supply_Air_Temperature_Setpoint_Limit
brick:Supply_Air_Temperature_Setpoint_Limit
brick:Limit
